# Generated by Django 5.2.8 on 2025-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
