# Generated by Django 5.2.8 on 2025-12-07 23:13

import apps.documents.models.documents
import apps.documents.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("STATE", "Nivel Estado"),
                            ("SCHOOL", "Nivel Colegio"),
                            ("TEACHER", "Nivel Docente"),
                            ("CLASSROOM", "Nivel Aula"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar como verdadero cuando esta categoría corresponda a normas oficiales del MINEDU/Estado.",
                    ),
                ),
                (
                    "minedu_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencia opcional usada por el MINEDU (familia, grupo, código interno).",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el documento se mantiene solo como histórico y se oculta de los flujos activos.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "official_code",
                    models.CharField(
                        blank=True,
                        help_text='Código corto de la norma, por ejemplo: "Ley 28044", "DS 011-2012-ED".',
                        max_length=100,
                    ),
                ),
                (
                    "official_number",
                    models.CharField(
                        blank=True,
                        help_text='Número oficial completo, por ejemplo: "RVM N° 123-2024-MINEDU".',
                        max_length=100,
                    ),
                ),
                (
                    "official_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Año de publicación de la norma.",
                        null=True,
                    ),
                ),
                (
                    "issuing_entity",
                    models.CharField(
                        blank=True,
                        help_text='Entidad emisora, por ejemplo: "MINEDU", "Congreso", "DRE Cusco".',
                        max_length=150,
                    ),
                ),
                (
                    "official_url",
                    models.URLField(
                        blank=True,
                        help_text="URL a la publicación oficial (gob.pe, El Peruano, MINEDU).",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la cual el documento se considera vigente.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual el documento es válido, si aplica.",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta norma se considera la referencia vigente.",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del documento.", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción o notas internas."
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Usuario propietario del documento.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Colegio asociado al documento, si aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="schools.school",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoría o familia del documento.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Nombre original del archivo subido o descargado.",
                        max_length=255,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo MIME detectado (application/pdf, docx, etc.).",
                        max_length=100,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Checksum opcional (SHA-256) para detectar duplicados.",
                        max_length=64,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de páginas para formatos paginados.",
                        null=True,
                    ),
                ),
                (
                    "structured_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Representación estructurada normalizada del documento (bloques: encabezados, párrafos, tablas, listas, etc.).",
                    ),
                ),
                (
                    "structured_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se generó o actualizó el contenido estructurado.",
                        null=True,
                    ),
                ),
                (
                    "is_structured_ready",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el contenido estructurado está listo para ser usado en RAG y en la vista procesada.",
                    ),
                ),
                (
                    "structured_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si falló el pipeline de contenido estructurado.",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="Resumen generado por IA."),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Verdadero cuando la versión ha sido troceada e indexada para IA.",
                    ),
                ),
                (
                    "indexing_error",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si falló el chunking/indexación.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo original (PDF o DOCX).",
                        upload_to=apps.documents.models.documents.DocumentVersion._document_file_path,
                        validators=[apps.documents.validators.validate_pdf_or_docx],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("ACTIVE", "En uso"),
                            ("HISTORICAL", "Histórico"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Subida por usuario"),
                            ("GENERATED", "Generada por IA"),
                            ("CRAWLED", "Obtenida desde fuente oficial"),
                        ],
                        default="UPLOAD",
                        help_text="Origen de esta versión.",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó esta versión.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Versión actualmente marcada como 'En uso'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentversion",
            ),
        ),
    ]
