# Generated by Django 5.2.8 on 2025-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="Contenido HTML completo listo para mostrar en el frontend (limpio y seguro).",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="html_error",
            field=models.TextField(
                blank=True,
                help_text="Mensaje de error si la generación/conversión a HTML falló (útil para debugging).",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="html_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento en que se generó o actualizó la versión HTML.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="html_toc",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Índice/tabla de contenidos (títulos, anchors, secciones) en formato JSON para navegación avanzada en el frontend.",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="is_html_ready",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el HTML está listo para ser mostrado al usuario (pipeline de conversión terminado correctamente).",
            ),
        ),
    ]
