# Generated by Django 5.2.9 on 2025-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentversion",
            name="indexing_error",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="is_indexed",
        ),
        migrations.AddField(
            model_name="documentversion",
            name="chunking_error",
            field=models.TextField(
                blank=True,
                help_text="Mensaje de error si falló el proceso de chunking.",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="chunking_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento en que se generaron los fragmentos por última vez.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="embeddings_error",
            field=models.TextField(
                blank=True,
                help_text="Mensaje de error si falló la generación de embeddings.",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="embeddings_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento en que se generaron los embeddings por última vez.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="is_chunking_ready",
            field=models.BooleanField(
                default=False,
                help_text="Verdadero cuando se generaron correctamente los fragmentos.",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="is_embeddings_ready",
            field=models.BooleanField(
                default=False,
                help_text="Verdadero cuando todos los fragmentos tienen embeddings.",
            ),
        ),
    ]
