# Generated by Django 5.2.8 on 2025-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "Document type",
                "verbose_name_plural": "Document types",
            },
        ),
    ]
