# Generated by Django 5.2.9 on 2025-12-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_documentversion_indexing_error_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentcategory",
            name="is_official",
        ),
    ]
