# Generated by Django 5.2.8 on 2025-11-30 19:50

import apps.documents.models
import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentversion_html_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=models.FileField(
                help_text="Archivo original (PDF o DOCX).",
                upload_to=apps.documents.models.document_file_path,
                validators=[apps.documents.validators.validate_pdf_or_docx],
            ),
        ),
    ]
