# Generated by Django 5.2.9 on 2025-12-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_remove_documentcategory_is_official"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentversion",
            name="ai_summary",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="chunking_error",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="chunking_generated_at",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="embeddings_error",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="embeddings_generated_at",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="is_chunking_ready",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="is_embeddings_ready",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="is_structured_ready",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="structured_content",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="structured_error",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="structured_generated_at",
        ),
    ]
