# Generated by Django 5.2.9 on 2025-12-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_documentversion_ai_summary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="school",
        ),
    ]
