# Generated by Django 5.2.8 on 2025-12-07 23:52

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CreateExtension("vector"),
    ]
