# Generated by Django 5.2.8 on 2025-12-07 23:53

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("documents_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Índice del fragmento (basado en 0)."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texto del fragmento listo para IA (párrafo, encabezado, tabla en markdown, etc.)."
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("PARAGRAPH", "Párrafo"),
                            ("HEADING", "Encabezado"),
                            ("TABLE", "Tabla"),
                            ("LIST", "Lista"),
                            ("OTHER", "Otro"),
                        ],
                        default="PARAGRAPH",
                        help_text="Tipo de fragmento (párrafo, tabla, encabezado, etc.).",
                        max_length=20,
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Número estimado de tokens.", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadatos opcionales (página, sección, ids de bloque, etc.).",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        help_text="Vector de embedding para búsqueda semántica (pgvector). La dimensión se configura a nivel de base de datos.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version_id", "index"],
                "unique_together": {("version", "index")},
            },
        ),
    ]
