from django.conf import settings
from django.db import models
from django.utils import timezone


class DocumentLevel(models.TextChoices):
    """Enumeration of all supported document levels."""

    STATE = "STATE", "Nivel Estado"
    SCHOOL = "SCHOOL", "Nivel Colegio"
    TEACHER = "TEACHER", "Nivel Docente"
    CLASSROOM = "CLASSROOM", "Nivel Aula"


class DocumentType(models.Model):
    """Configuration model describing a document type.

    A document type defines metadata and constraints used across documents,
    such as level (state, school, teacher, classroom) and whether it is an
    official MINEDU-related document.
    """

    code = models.SlugField(unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    level = models.CharField(
        max_length=20,
        choices=DocumentLevel.choices,
    )
    is_official = models.BooleanField(default=False)
    minedu_reference = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = "Document type"
        verbose_name_plural = "Document types"
        ordering = ["level", "name"]

    def __str__(self) -> str:
        """Return a readable representation of the document type."""

        return f"{self.name} ({self.get_level_display()})"


class Document(models.Model):
    """Main document entity used across the Korena system.

    A Document belongs to a user (owner) and optionally to a school,
    is associated with a DocumentType, and maintains a reference to its
    current active version.
    """

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="documents",
    )
    school = models.ForeignKey(
        "schools.School",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="documents",
    )
    type = models.ForeignKey(
        DocumentType,
        on_delete=models.PROTECT,
        related_name="documents",
    )

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    current_version = models.ForeignKey(
        "DocumentVersion",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )

    is_archived = models.BooleanField(default=False)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        """Return the document title as its string representation."""

        return self.title


class DocumentVersionStatus(models.TextChoices):
    """Enumeration of possible states for a document version."""

    DRAFT = "DRAFT", "Borrador"
    ACTIVE = "ACTIVE", "En uso"
    HISTORICAL = "HISTORICAL", "Histórico"


def document_file_path(instance: "DocumentVersion", filename: str) -> str:
    """Build a deterministic file path for document uploads.

    The path groups files under the document ID and prefixes the filename
    with a timestamp to avoid collisions.

    Args:
        instance (DocumentVersion): The version instance that owns the file.
        filename (str): Original uploaded filename.

    Returns:
        str: Relative path where the file will be stored.
    """
    timestamp = timezone.now().strftime("%Y%m%d%H%M%S")

    return f"documents/{instance.document_id}/{timestamp}_{filename}"


class DocumentVersion(models.Model):
    """Represents a single version of a document.

    Each version holds a file, status, metadata such as AI-generated summary,
    and origin (user upload or generated by AI).
    """

    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name="versions",
    )
    file = models.FileField(upload_to=document_file_path)
    status = models.CharField(
        max_length=20,
        choices=DocumentVersionStatus.choices,
        default=DocumentVersionStatus.DRAFT,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="document_versions_created",
    )
    created_at = models.DateTimeField(default=timezone.now)

    ai_summary = models.TextField(blank=True)
    page_count = models.PositiveIntegerField(null=True, blank=True)
    source = models.CharField(
        max_length=20,
        choices=(
            ("UPLOAD", "Subida por usuario"),
            ("GENERATED", "Generada por IA"),
        ),
        default="UPLOAD",
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        """Return a readable representation including title, ID and status."""

        return f"{self.document.title} v{self.pk} [{self.status}]"
