# Generated by Django 5.2.8 on 2025-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planningsheet",
            options={"ordering": ["-created_at"]},
        ),
    ]
